### ISSUE TITLE
Missing version suffixes when publishing SBT plugin to Maven repo

### ISSUE THREAD

**Issue by davegurnell** [sbt/sbt-bintray#81]
Hello,

Is it possible to publish SBT plugins to Maven-style repos? I've got this project that I recently converted to `bintray-sbt`:

https://github.com/untyped/sbt-plugins

When I publish to our Bintray, the artefacts end up without version suffixes. This means people can't require them via `addSbtPlugin(...)`:

http://dl.bintray.com/untyped/maven/com/untyped/sbt-js/0.8/

I used to publish the artefacts to a private server but I'd like to move them to Bintray. I don't want to submit them to the central plugins repo because there are lots of other plugins that do the same thing.

Any ideas how I can fix this? Do I need to set up an Ivy-style repo instead, maybe?

Thanks for your help!

**Comment by davegurnell** [comment]
I've resolved this by converting the repo to Ivy format. It'd be useful to know whether this is a requirement for publishing SBT plugins, or if I was missing something more subtle. Problem solved for now, though, so I'll close this ticket.

**Comment by softprops** [comment]
This is a restriction for sbt plugins in general and not specific to publishing to bintray. The reason is that sbt has two axis of cross versioning. One for the binary version of scala sbt uses amd one for the binary release of sbt itself because sbt changes can cause plugin incompatibility. It stores the sbt cross version in ivy metadata which is why you can't publish sbt plugins to mvn style repos.

**Comment by davegurnell** [comment]
Thanks Doug. That's useful to know!

**Comment by softprops** [comment]
np. I tried to find a link some docs for that on sbt's website but couldn't find anything :/

**Comment by jvican** [comment]
This is still an issue and I believe that we can change the maven repository to put those version suffixes in the right place. We do have access to that information because it's exposed via default sbt keys.
